//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveSchoolCurse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.drivingLesson = new HashSet<drivingLesson>();
            this.StudentAndGroup = new HashSet<StudentAndGroup>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<int> idDiscount { get; set; }
        public Nullable<bool> isExam { get; set; }
        public Nullable<bool> isTheory { get; set; }
        public Nullable<int> idCategory { get; set; }
    
        public virtual category category { get; set; }
        public virtual discount discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<drivingLesson> drivingLesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAndGroup> StudentAndGroup { get; set; }
    }
}
