//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveSchoolCurse
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAndGroup
    {
        public int id { get; set; }
        public Nullable<int> idStudent { get; set; }
        public Nullable<int> idGroup { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual studGroup studGroup { get; set; }
    }
}
